### PR TITLE
catch lib crash when call rpc without args closes #63

### LINKED ISSUE #63: Peer Rpc call default values to args
Hello , 
If  you dont specify any arg  in rpc call  like this: 
```js
b.rpc(address, callname, args, callback);
```
you end up with error on remote peer (destination of rpc call) 
```
Cannot read properties of undefined (reading 'toString')
```

I think it should have a default empty object if user not specify args..

### PR DESCRIPTION
**Pull request by Kos-M**
closes #63

Prefered args to left null  (as it is in catch block)  instead of an empty object  , because that  leads to  another crashing in another line ( if a recall corectly , in a JSON.parse  line )

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -143,6 +143,32 @@ test("RPC and message passing", function(t) {
...
 
+test("RPC Call without passing any message/data", function(t) {
+  t.plan(5);
+
+  const bs = new Bugout({dht: false, tracker: false});
+  const bc = new Bugout(bs.address(), {dht: false, tracker: false});
+
+  bs.register("call_without_args", function(pk,args){
+    console.dir(args)
+    t.assert(args === null , 'args should be null , when called without args from another peer')
```
Comment (chr15m) [inline test.js:154]: Small typo: there shouldn't be a space after the word "null".

**Review by chr15m — CHANGES_REQUESTED** [review]
Thanks for the fix @Kos-M. I think it could be simplified to change line 338 to:

```javascript
var argsstring = packet.a ? packet.a.toString() : "null";
```

Can you try that and see if your new test still passes?

File: test.js (hunk 1 above)
Comment (Kos-M) [reply test.js]: correct :)

**Comment by Kos-M** [comment]
Simplified checks , as you suggested ( better that way) .
Tests for this case , all pass.
Not related on this , some tests fails , some with errors in  plan ( not correct statement of total assertions  , i think ) 
and some others with message like : ```not ok 63 bTwbdRC1EQxxkwY9vMr2dRRbPAZNWp2Rzh left unexpectedly```
They are not related with my changes , as i noticed before start working on this. Maybe should open another issue for them..

**Comment by Kos-M** [comment]
Any update on this @chr15m  ?
Do you need any other change ? (:

**Comment by chr15m** [comment]
I'm on the road but will try to review & merge soon.

**Comment by Kos-M** [comment]
Sure , just checking if i was missing somthing , drive safe!

File: index.js [hunk 2]
```diff
@@ -335,8 +335,8 @@ function onMessage(bugout, identifier, wire, message) {
         } else if (packet.y == "r") { // rpc call
           debug("rpc", identifier, packet);
           var call = packet.c.toString();
-          var argsstring = packet.a.toString();
           try {
+            var argsstring = packet["a"] ? packet.a.toString() : "null";
```
Comment (chr15m) [inline index.js:339]: Can you move this out of the try block?

**Review by chr15m — CHANGES_REQUESTED** [review]
Will merge after this small change, thanks!

File: index.js (hunk 2 above)
Comment (Kos-M) [reply index.js:339]: of course , i ll make that change next minutes..

**Comment by Kos-M** [comment]
ready  :+1:

**Comment by chr15m** [comment]
Thanks for this fix and for your patience.

**Comment by Kos-M** [comment]
My pleasure @chr15m   :smile:
